
function member_email_check() {
    if (document.getElementById("email-id").value == "jb440422@gmail.com" || document.getElementById("email-id").value == "jamesharrington.jbh3@gmail.com" ||
document.getElementById("email-id").value == "tajaglover88@gmail.com" document.getElementById("email-id").value == "colleenalleyne@hotmail.com" ||document.getElementById("email-id").value == "ikitty3@gmail.com" ||
document.getElementById("email-id").value == "mingos35@verizon.net" ||document.getElementById("email-id").value == "gboydsr@verizon.net" ||document.getElementById("email-id").value == "tasha916@gmail.com" ||document.getElementById("email-id").value == "journeybrooks13@gmail.com" ||document.getElementById("email-id").value == "noweaponformed57@gmail.com" ||document.getElementById("email-id").value == "vickieelaine666@yahoo.com" ||document.getElementById("email-id").value == "lcampbell320@yahoo.com" ||document.getElementById("email-id").value == "impactseed@yahoo.com" ||document.getElementById("email-id").value == "mcave1999@gmail.com" ||document.getElementById("email-id").value == "mardunmoodie@gmail.com" ||document.getElementById("email-id").value == "felespn@yahoo.com" ||
document.getElementById("email-id").value == "eedwardstrina@yahoo.com" ||document.getElementById("email-id").value == "nfairfax@censuschannel.com" ||document.getElementById("email-id").value == "wllsrve@aol.com" ||
document.getElementById("email-id").value == "zernnak@aol.com" ||
document.getElementById("email-id").value == "philandjulie2014@gmail.com" ||document.getElementById("email-id").value == "phsrf88@yahoo.com" ||
document.getElementById("email-id").value == "mhartman@ak9i.com" ||
document.getElementById("email-id").value == "panamapraise@verizon.net" ||document.getElementById("email-id").value == "bill_haynes@yahoo.com" ||document.getElementById("email-id").value == "houseofhaynes@msn.com" ||document.getElementById("email-id").value == "benjamin.haynes.13@cnu.edu" ||document.getElementById("email-id").value == "ja_haynes@gmx.com" ||
document.getElementById("email-id").value == "hedgepethndn@cox.net" ||document.getElementById("email-id").value == "nccutie2009@gmail.com" ||document.getElementById("email-id").value == "raquanH94@gmail.com" ||document.getElementById("email-id").value == "jchuber@verizon.net" ||document.getElementById("email-id").value == "rhuber29fan@cox.net" ||document.getElementById("email-id").value == "onemomof3@cox.net" ||
document.getElementById("email-id").value == "matthew.huber@nnschools.org" ||document.getElementById("email-id").value == "fredj.jackson1953@gmail.com" ||document.getElementById("email-id").value == "Michelle82862@gmail.com" ||document.getElementById("email-id").value == "ywp7770@msn.com" ||
document.getElementById("email-id").value == "ros505@msn.com" ||
document.getElementById("email-id").value == "rook0713@gmail.com" ||document.getElementById("email-id").value == "pokeyslows@gmail.com" ||document.getElementById("email-id").value == "cheyla.hairston@yahoo.com" ||document.getElementById("email-id").value == "austinmccaffrey@yahoo.com" ||document.getElementById("email-id").value == "mariadelcid050796@gmail.com" ||document.getElementById("email-id").value == "jayda.mckinney@gmail.com" ||document.getElementById("email-id").value == "daneya@verizon.net" ||document.getElementById("email-id").value == "yurikparker7@gmail.com" ||document.getElementById("email-id").value == "peterfalk895@gmail.com" ||document.getElementById("email-id").value == "A.Parker74@outlook.com" ||document.getElementById("email-id").value == "angelafaith@cox.net" ||document.getElementById("email-id").value == "pattersonconnie@msn.com" ||document.getElementById("email-id").value == "gpiatt08@cox.net" ||
document.getElementById("email-id").value == "kshouldis87@yahoo.com" ||document.getElementById("email-id").value == "hrvckgirl@yahoo.com" ||document.getElementById("email-id").value == "gagesmith.gage@yahoo.com" ||document.getElementById("email-id").value == "noweaponformed81@gmail.com" ||document.getElementById("email-id").value == "kartin8390@yahoo.com" ||document.getElementById("email-id").value == "donnaterry85@gmail.com" ||document.getElementById("email-id").value == "reina_40@yahoo.com" ||document.getElementById("email-id").value == "christhomas@artfullyrandom.com" ||document.getElementById("email-id").value == "watersof07@aol.com" ||document.getElementById("email-id").value == "tnf.jamaica@yahoo.com" ||document.getElementById("email-id").value == "earlncat@yahoo.com" ||document.getElementById("email-id").value == "GDZGIRL1974@yahoo.com" ||document.getElementById("email-id").value == "debbiec1000@yahoo.com" ||document.getElementById("email-id").value == "jo.joe.no9@gmail.com" ||document.getElementById("email-id").value == "visionleader24@gmail.com" ||document.getElementById("email-id").value == "sha9lnon@gmail.com" ||document.getElementById("email-id").value == "euricawhite@gmail.com" ||document.getElementById("email-id").value == "alffonzo6branch@gmail.com" ||document.getElementById("email-id").value == "JimWindman2020@gmail.com" ||document.getElementById("email-id").value == "tandnearl@yahoo.com") {
        //REMOVE ALREADY MEMBER CONTAINER
        document.getElementById("already-a-member-container-id").style.display = "none";
        //ADD VERIFICATION SUCCESSFULT CONTAINER
        document.getElementById("verification-successful-container-id").style.display = "block";
    } else {
        document.getElementById("couldnt-verify-err-id").style.display = "block";
    }
}

